# Custom Language File for Launcher Customizer

[ejs.app]
title = "MCT Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/SwagSteve/MCT-Launcher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/n6kSXmQwVJ"
teamPlayersHeader = "Players"
# Set this to your hosted endpoint, e.g. "https://yourdomain.com/teams.php"
teamDataURL = "http://132.145.24.15/api/teams.php"

[ejs.settings]
sourceGithubLink = "https://github.com/SwagSteve/MCT-Launcher"
supportLink = "https://github.com/SwagSteve/MCT-Launcher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO MCT"
welcomeDescription = ""
welcomeDescCTA = ""